### ISSUE TITLE
send values 

### ISSUE THREAD

**Issue by DobbyAkhmadi** [minhdtb/IEC-60870#1]
# how to send to display IEC-60870-104 sir?

i'm running this app , just get value from display iec and i'cant send values to iec emulator .

**Comment by Jeprotec** [comment]
I have the same problem.
Do you have a program example for input and output control?

**Comment by gcmvanloon** [comment]
You need to modify the code in order to enable sending stuff.
`ClientSAP` class has a private `_connection` field. When you expose this connection you can use it's `Send` method to send data (ASdu's). Or you can add a send method on the ClientSAP and leave the _connection private. I've modified the `Connect` method to return the `Connection`. It's in my fork if you want to take a look.
It's just a small modification that is easy to do.

**Comment by minhdtb** [comment]
I have added this function on 1.2 release, please refer https://github.com/minhdtb/IEC-60870/releases/tag/1.2 The solutions as gcmvanloon said. Thanks for all support
